import citiesData from '@/data/cities.json';
import { MONTHS } from '@/lib/calendar';

/**
 * Representative cities per zone with NOAA station frost dates. Generated by
 * scripts/fetch-noaa.mjs — see the note in cities.json. Every value on a zone
 * page's city table comes from here.
 */
export interface FrostProbabilities {
  p50: string | null;
  p30: string | null;
  p10: string | null;
}

export interface City {
  city: string;
  state: string;
  zone: number | null;
  subzone: string | null;
  minTempF: number | null;
  lastFrost: FrostProbabilities;
  firstFrost: FrostProbabilities;
  frostFreeDays: number | null;
  /** Share of years with any 32°F freeze at the station. */
  freezeChancePct: number | null;
  station: { id: string; name: string; lat: number; lon: number };
  source: string;
  zoneSource: string;
}

export const cities = citiesData.cities as City[];
export const citiesMeta = { note: citiesData.note, sources: citiesData.sources };

// Brief rule: no number without a source line. Enforced at build time — any page
// importing this module fails the build if a row carries a value it cannot cite.
for (const c of cities) {
  const frostValues = [
    ...Object.values(c.lastFrost), ...Object.values(c.firstFrost),
    c.frostFreeDays, c.freezeChancePct,
  ].filter((v) => v !== null);
  if (frostValues.length > 0 && !/^https:\/\/www\.ncei\.noaa\.gov\//.test(c.source ?? '')) {
    throw new Error(`cities.json: ${c.city}, ${c.state} has frost values but no NOAA source`);
  }
  if ((c.zone !== null || c.subzone !== null) && !c.zoneSource) {
    throw new Error(`cities.json: ${c.city}, ${c.state} has a zone but no zoneSource`);
  }
}

/**
 * Below this share of freeze years the "50% date" describes rare cold snaps,
 * not a typical winter, so the table says how often it freezes instead.
 */
export const TYPICAL_FREEZE_MIN_PCT = 50;

export const hasTypicalFrost = (c: City) =>
  c.freezeChancePct === null || c.freezeChancePct >= TYPICAL_FREEZE_MIN_PCT;

export function citiesForZone(zone: number): City[] {
  return cities.filter((c) => c.zone === zone);
}

/** "03-15" -> "Mar 15". */
export function formatMonthDay(mmdd: string): string {
  const [m, d] = mmdd.split('-').map(Number);
  return `${MONTHS[m - 1].slice(0, 3)} ${d}`;
}

/** "03-15" -> day of year in a non-leap year. */
export function dayOfYear(mmdd: string): number {
  const cum = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
  const [m, d] = mmdd.split('-').map(Number);
  return cum[m - 1] + d;
}

/** Link that opens the calendar tool pre-filled with a city's typical frost dates. */
export function toolLink(c: City, zone: number): string | null {
  if (!hasTypicalFrost(c) || !c.lastFrost.p50 || !c.firstFrost.p50) return null;
  return `/planting-calendar/?zone=${zone}&last=${c.lastFrost.p50}&first=${c.firstFrost.p50}#calendar-tool`;
}
